### ISSUE TITLE
Add pressio demo apps to github workflow

### ISSUE THREAD

**Issue by eparish1** [Pressio/rom-tools-and-workflows-demos#3]
As far as I can understand, In order for the documentation for this[ branch, which has a PDA demo,](https://github.com/Pressio/rom-tools-and-workflows-demos/pull/1) to be able to deploy, we will need to have pressio-demo-apps be installed as part of the CI. 

If we could add this to the CI, I can go in and update the branch to work with it.

**Comment by fnrizzi** [comment]
What do you mean deploy this? 
You want this demo to be tested in the CI or want the demo page served online?

**Comment by eparish1** [comment]
The demo uses jupyter notebooks. For the way the website is built, the [deploy_docs.yaml ](https://github.com/Pressio/rom-tools-and-workflows-demos/blob/main/.github/workflows/deploy_docs.yml) needs to execute python and run the script. Does that make sense?
